LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
--USE IEEE.STD_LOGIC_UNSIGNED.ALL; -- Quartus
USE IEEE.NUMERIC_STD.ALL; -- GHDL

ENTITY DECREMENTAR IS
	PORT (E1: IN STD_LOGIC_VECTOR(7 DOWNTO 0);
			S: OUT STD_LOGIC_VECTOR(7 DOWNTO 0));
END DECREMENTAR;

ARCHITECTURE DECREMENTAR_ARCH OF DECREMENTAR IS
BEGIN
	--S <= E1 - 1; -- Quartus
	S <= STD_LOGIC_VECTOR( UNSIGNED(E1) - 1 );
END DECREMENTAR_ARCH;